new_topic_button_icon:
  default: "plus"
new_topic_button_text:
  default: "New Topic"
new_topic_button_title:
  default: ""
hide_default_button:
  default: true
show_to_anon:
  default: false
open_composer_without_category:
  default: false
